
@startuml
title /Spot service: Spotting and Queuing \n and Last Mile Dispatching for Open-Autonomy\n V0.7


'V0.7 - Jan. 2023

	'Participant "Dispatcher\n(Person)" as dispatch
 	participant "Fleet Management\n(server)" as fms

	'participant "Public /Map service" as map
	participant "Onboard Autonomy\n(Vehicle) Truck-3" as uht3
	participant "Onboard Autonomy\n(Vehicle) Truck-2" as uht2
	participant "Onboard Autonomy\n(Vehicle) Truck-1" as uht1
	participant "AHS\n(Client)" as ahs

box "HP solution with Spot Service" #EEEEFF
  participant "Public Interface\n/Spot Service" as spot
	participant "Place\n database" as pdb
	'participant "Last Mile\nDispatching" as lmd
	participant "Proprietary HP\nShovel\nVehicle 77" as sho
end box



autonumber

== Initial connection ==
ahs -> spot: Connect with wss://
spot -> ahs: [[https://github.com/open-autonomy/spot/blob/main/specification/ServiceIdentification.md#spotservicev1 ServiceIdentification]]
spot -> ahs: FleetDefinitionV2 (All HP systems)
ahs -> spot: FleetDefinitionV2 (All Autonomous trucks)
pdb -> spot: Here's a copy of all the database
spot -> ahs: PlaceSummaryV1
spot -> ahs: PlaceAllV1
...

== Periodic ==
ahs -> spot: VehiclePositionV1 (where are the trucks)
spot -> ahs: VehiclePositionV1 (where are the HP vehicles)

== Operational Cycle ==
fms -> ahs: HaulTruckAssignmentRequest for Truck-1 Loading at Shovel(77) in Area(L1) following this route{...,111}
ahs -> uht1: Follow this route to reach Area(L1), then plot a path to Shovel(77).
fms -> ahs: HaulTruckAssignmentRequest for Truck-2 Loading at Shovel(77) in Area(L1) following this route{...,111}
ahs -> uht2: Follow this route and reach Area(L1), then get loaded at Shovel(77).
fms -> ahs: HaulTruckAssignmentRequest for Truck-3 Loading at Shovel(77) in Area(L1) following this route{...,111}
ahs -> uht3: Follow this route and reach Area(L1), then get loaded at Shovel(77).

uht1 -[#blue]> ahs: Hey boss, I'm near the end of the Haul Road, what do I do?
ahs -[#blue]> spot: ApproachingLastMileV1(Truck-1, 111, Equipment, #077 )
spot -[#blue]> ahs: OccupyPlace( Truck-1, QueueIDPrimary=Q1,\n QueueIDStage=null, SpotId=S1)\n + S1 object + Q1 object
pdb -> spot: The spot S1 has changed state from Next to Reserved\n and both Q1 and S1 have ChangeSequence change.
spot -> ahs: PlaceUpdated(S1 State=Reserved, sequence=X++, ...)
spot -> ahs: PlaceUpdated(Q1 CapacityUsed=1, sequence=X++, ...)
ahs -[#blue]> uht1: All right, I'm told you can whizz through {Q1 object}\n and continue to spot at this place: {S1 object}

uht2 -[#orange]> ahs: Hey boss, I'm near the end of the Haul Road, what do I do?
ahs -[#orange]> spot: ApproachingLastMileV1(Truck-2, 111, Equipment, #077 )
spot -[#orange]> ahs: OccupyPlace( Truck-1, QueueIDPrimary=Q1,\n QueueIDStage=null, SpotId=0)\n + Q1 object
spot -> ahs: PlaceUpdated(Q1 CapacityUsed=2, sequence=X++, ...)
ahs -[#orange]> uht2: All right, I'm told you can queue at {Q1 object}

uht1 -[#blue]> ahs: My front has just crossed the position of Q1
ahs -[#blue]> spot: OccupyingPlaceV1(Truck-1, Q1)
spot -> ahs: PlaceUpdated(Q1 Servicing=Truck-1, sequence=X++, ...)

uht1 -[#blue]> ahs: My rear has just cleared the position of Q1
ahs -[#blue]> spot: LeftPlaceV1(Truck-1, Q1)
spot -> ahs: PlaceUpdated(Q1 CapacityUsed=1, Servicing=null, ServiceCount++, Sequence=X++, ...)


uht3 -[#green]> ahs: Hey boss, I'm near the end of the Haul Road, what do I do?
ahs -[#green]> spot: ApproachingLastMileV1(Truck-3, 111, Equipment, #077 )
spot -[#green]> ahs: OccupyPlace( Truck-3, QueueIDPrimary=Q1,\n QueueIDStage=null, SpotId=0)\n + Q1 object
spot -> ahs: PlaceUpdated(Q1 CapacityUsed=2, sequence=X++, ...)
ahs -[#green]> uht3: All right, I'm told you can queue at {Q1 object}

uht1 -[#blue]> ahs: My load origin is at the position of S1\n and I'm staying here until I'm told to leave.
ahs -[#blue]> spot: OccupyingPlaceV1(Truck-1, S1)
spot -> ahs: PlaceUpdated(S1 SpotState=Full, Servicing=Truck-1, sequence=X++, ...)
spot -> sho: Truck-1 is spotted and ready to be loaded.

uht2 -[#orange]> ahs: My front has just crossed the position of Q1\n and I'm waiting here becasue I have no more permission to continue.
ahs -[#orange]> spot: OccupyingPlaceV1(Truck-1, Q1)
ahs -[#orange]> uht2: Yeah, hang in there, I'll tell you when you can spot.



@enduml
